### Linguagens de Programação para Ciência de Dados
#### NumPy

Exercícios - Lista 02

Exercício 8: Usando NumPy, importe o dataset iris mantendo o seu conteúdo intacto.

In [43]:
import numpy as np  # Importa a biblioteca NumPy para seu projeto


iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii')

#Se digitar somente print iris, vai imprimir toda a matriz

#iris[:2,4] # vai trazer 2 registros da coluna 4

#iris [:3] #imprime somente as 3 primeiras linhas

sepallength=iris[:,0].astype(float)
print(sepallength)





[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


Exercicio 9: Extraia a coluna species do dataset importado na questão anterior para um vetor unidimensional.

In [44]:
species=iris[:,4].astype(str)
print(species)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

Exercício 10
Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.

In [45]:

#para fazer a mediana np.median(sepallength)
mediana_sepallength=np.median(sepallength)
print('A mediana da primeira coluna é:',mediana_sepallength)

print("A média da primeira coluna é é:",np.mean(sepallength))

print("Desvio padrao da primeira coluna é:",np.std(sepallength))


A mediana da primeira coluna é: 5.8
A média da primeira coluna é é: 5.843333333333334
Desvio padrao da primeira coluna é: 0.8253012917851409


Exercício 11
Normalize a coluna (sepallength) do dataset iris de tal forma que o valor mínimo seja zero (0) e o valor máximo seja 1.


In [46]:
sepal_length_max=sepallength.max()
sepal_length_min=sepallength.min()

#Método 1
sepallength_normalizada=(sepallength-sepal_length_min) / (sepal_length_max-sepal_length_min)

print('valor  é', sepallength[:2])
print('valor máximo é:', sepallength_normalizada[:2])


valor  é [5.1 4.9]
valor máximo é: [0.22222222 0.16666667]


Exercício 12
Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris.

In [47]:
np.percentile(sepallength, q=[5,95])


array([4.6  , 7.255])

Exercício 13:
Encontre a quantidade de valores ausentes, bem como a posição deles da primeira coluna da coluna comprimento das pétalas (sepallength), dentro do vetor abaixo:

In [48]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Quantidade de valores ausentes:",np.isnan(iris_2d[:,0]).sum())
print("Posicao deos valores ausentes:", np.where(np.isnan(iris_2d[:,0])))

Quantidade de valores ausentes: 5
Posicao deos valores ausentes: (array([ 38,  80,  91, 113, 121], dtype=int64),)


Exercicio 14:
Filtre o vetor iris_2d do exercício anterior para que ele tenha: (terceira coluna (petallength) > 1.5) && (primeira coluna (sepallength) < 5.0)

In [49]:
iris_2d = np.genfromtxt(iris_dataset_url, delimiter=",", dtype='float',usecols=[0,1,2,3], encoding='ascii')
condicao=(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
iris_2d[condicao]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

Exercício 15:
Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

In [50]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

any_nan_in_row=np.array([~np.any(np.isnan(row))for row in iris_2d])
iris_2d[any_nan_in_row][:5]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

Exercíco 16: Encontre a correlação entre a primeira coluna (sepallength) e a (terceira coluna (petallength) no vetor iris_2d.

In [51]:
#Correlação entre sepallength e petallength

petallength = iris[:,3].astype(float)

correl = np.corrcoef(sepallength,petallength)
print(correl)


[[1.         0.81795363]
 [0.81795363 1.        ]]


Exercício 17: Verifique se o vetor iris_2d possui qualquer valor faltante, caso possui deverá retornar True caso contrário False.

In [52]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()


False

Exercicio 18: Substitua todas as ocorrências de nan (Not a Number) por zeros em um vetor NumPy.

In [53]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

#imprime na tela os numeros faltantes e suas localizaçoes
print("Quantidade de numeros faltantes:",np.isnan(iris_2d).sum())
print("Localizaçao dos faltantes:", np.where(np.isnan(iris_2d)))


#substitui os nan por 0
iris_2d[np.isnan(iris_2d)] = 0

print("Quantidade de numeros faltantes após substituição:",np.isnan(iris_2d).sum())


Quantidade de numeros faltantes: 19
Localizaçao dos faltantes: (array([  0,   5,  33,  36,  38,  43,  58,  70,  71,  76,  84,  94,  95,
       102, 105, 114, 119, 131, 138], dtype=int64), array([1, 2, 1, 2, 3, 0, 2, 2, 0, 1, 1, 3, 1, 2, 1, 0, 0, 3, 2],
      dtype=int64))
Quantidade de numeros faltantes após substituição: 0


Exercicio 19: Encontre e conte os valores únicos da coluna species

In [54]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#captura a quantidade de valores unicos em de cada tipo de especies.
valor = np.array(np.unique(iris[:,4], return_counts=True)).T
for nome, quant in valor:
    print("O tipo",nome,"apareceu",quant, "vezes")


O tipo b'Iris-setosa' apareceu 50 vezes
O tipo b'Iris-versicolor' apareceu 50 vezes
O tipo b'Iris-virginica' apareceu 50 vezes


Exercicio 20: Mapeie terceira coluna (petallength) de tal forma que os valores numéricos sejam substituídos por valores textuais, seguindo de acordo com a tabela abaixo:

Número 	Classificação
Menor do que 3 	Pequena
entre 3 e 5 	Média
Maior ou Igual a 5 	Grande

In [55]:
petal_length_intervalos = np.digitize(iris[:,2].astype('float'), [0,3,5,10])
mapeamento_rotulos = {1:'Pequeno', 2:'Medio', 3:'Grande', 4:np.nan}
petal_length_categorizada = [mapeamento_rotulos[i] for i in petal_length_intervalos]
petal_length_categorizada


['Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Pequeno',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Grande',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Grande',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio',
 'Medio'

Exercício 21: Crie uma nova coluna chamada volume, preenchida com dados resultantes da seguinte equação:

𝑣𝑜𝑙𝑢𝑚𝑒=( 𝑃𝑖 𝑥 𝑃𝑒𝑡𝑎𝑙𝑙𝑒𝑛𝑔𝑡ℎ 𝑥 𝑆𝑒𝑝𝑎𝑙𝐿𝑒𝑛𝑔𝑡ℎ2 )/3

In [56]:
# Entrada

import math

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

volume = (math.pi * petallength * (sepallength**2))/3

#foi inserido na 5 coluna os valores de volume
iris_4d = np.insert(iris_2d, 5,volume, axis=1)
print(iris_4d)


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 5.447521661324701]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 5.028642640846063]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 4.62651878118657]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 4.431740036664]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 5.235987755982989]
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa' 12.214512237157116]
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa' 6.647610054996001]
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa' 5.235987755982989]
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa' 4.054748918233227]
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa' 2.5143213204230315]
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa' 6.107256118578558]
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa' 4.825486315913922]
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa' 2.412743157956961]
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa' 1.9362682721625089]
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa' 7.045545124450709]
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-seto

Exercício 22: Usando NumPy e o dataset iris responda: Qual é o segundo maior valor de comprimento de pétala (petallength) da espécie setosa?

In [57]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#ordena a lista do maior para o menor e salva em uma variavel
ordenada = sorted(iris[:,2], reverse=True)
print("O segundo maior valor é:",ordenada[1])


O segundo maior valor é: b'6.7'


Exercício 23: Ordene o dataset iris com base na coluna sepallength de maneira crescente.

In [58]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#a funçao sorted ordena o dataset em ordem crescente pela coluna sepallength
sorted(iris, key=lambda sepallength:sepallength[0])

[array([b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'], dtype=object),
 array([b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'], dtype=object),
 array([b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'], dtype=object),
 array([b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'], dtype=object),
 array([b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'], dtype=object),
 array([b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'], dtype=object),
 array([b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'], dtype=object),
 array([b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'], dtype=object),
 array([b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'], dtype=object),
 array([b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'], dtype=object),
 array([b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'], dtype=object),
 array([b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'], dtype=object),
 array([b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'], dtype=object),
 array([b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'], dtype=o

Exercício 24: Encontre o valor mais frequente da terceira coluna (petallength) do dataset iris.

In [59]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#faz a contagem dos valores da coluna
unique,count = np.unique(iris[:,2],return_counts=True)

#Converte em um dicinoario
val = dict(zip(unique,count))

#busca o maior numero de repeticação
m_freq = max(val, key=val.get)
print("O valor mais frequente foi:", m_freq)

O valor mais frequente foi: b'1.5'


Exercício 25: Encontre a posição da primeira ocorrência de um valor maior do que 1.0 da quarta coluna (petalwidth) do dataset iris.

In [60]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

np.argwhere(iris[:,3].astype(float)>1.0)[0]

array([50], dtype=int64)

Exercício 26: Obtenha a posição dos top 5 valores maíximos do vetor abaixo:

In [61]:
# Entrada
np.random.seed(100)
vetor = np.random.uniform(1,50, 20)

vetor_ord = sorted(vetor, reverse=True)
vetor_ord[:5]

[48.95256545066111,
 44.674775761300936,
 42.39403048367528,
 41.46678500014733,
 40.99501268756616]

Exercício 27: Encontre a média de uma coluna numérica agrupada por uma coluna categórica em uma matriz (vetor numpy 2D)

In [62]:
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Saída Esperada
#>  [[b'Iris-setosa', 3.418],
#>  [b'Iris-versicolor', 2.770],
#>  [b'Iris-virginica', 2.974]]


categoria = np.unique(iris[:,4])
i = 0

for x in categoria:
    categ = iris[iris[:,4]== x]
    print(categoria[i], "{:.3f}".format(np.mean(categ[:,1].astype(float))))
    i+=1

b'Iris-setosa' 3.418
b'Iris-versicolor' 2.770
b'Iris-virginica' 2.974
